# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/small.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/small.proto',
  package='ord',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x11proto/small.proto\x12\x03ord\"8\n\x08Reaction\x12,\n\x0bidentifiers\x18\x01 \x03(\x0b\x32\x17.ord.ReactionIdentifier\"\x90\x02\n\x12ReactionIdentifier\x12\x34\n\x04type\x18\x01 \x01(\x0e\x32&.ord.ReactionIdentifier.IdentifierType\x12\x0f\n\x07\x64\x65tails\x18\x02 \x01(\t\x12\x0f\n\x05value\x18\x03 \x01(\tH\x00\x12\x15\n\x0b\x62ytes_value\x18\x04 \x01(\x0cH\x00\"\x82\x01\n\x0eIdentifierType\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\n\n\x06\x43USTOM\x10\x01\x12\x13\n\x0fREACTION_SMILES\x10\x02\x12\x16\n\x12\x41TOM_MAPPED_SMILES\x10\x03\x12\n\n\x06RINCHI\x10\x04\x12\x08\n\x04NAME\x10\x05\x12\x10\n\x0cRDKIT_BINARY\x10\x06\x42\x06\n\x04kindb\x06proto3'
)



_REACTIONIDENTIFIER_IDENTIFIERTYPE = _descriptor.EnumDescriptor(
  name='IdentifierType',
  full_name='ord.ReactionIdentifier.IdentifierType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CUSTOM', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REACTION_SMILES', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ATOM_MAPPED_SMILES', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RINCHI', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NAME', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RDKIT_BINARY', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=219,
  serialized_end=349,
)
_sym_db.RegisterEnumDescriptor(_REACTIONIDENTIFIER_IDENTIFIERTYPE)


_REACTION = _descriptor.Descriptor(
  name='Reaction',
  full_name='ord.Reaction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='identifiers', full_name='ord.Reaction.identifiers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=82,
)


_REACTIONIDENTIFIER = _descriptor.Descriptor(
  name='ReactionIdentifier',
  full_name='ord.ReactionIdentifier',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='ord.ReactionIdentifier.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='details', full_name='ord.ReactionIdentifier.details', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='ord.ReactionIdentifier.value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bytes_value', full_name='ord.ReactionIdentifier.bytes_value', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REACTIONIDENTIFIER_IDENTIFIERTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='kind', full_name='ord.ReactionIdentifier.kind',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=85,
  serialized_end=357,
)

_REACTION.fields_by_name['identifiers'].message_type = _REACTIONIDENTIFIER
_REACTIONIDENTIFIER.fields_by_name['type'].enum_type = _REACTIONIDENTIFIER_IDENTIFIERTYPE
_REACTIONIDENTIFIER_IDENTIFIERTYPE.containing_type = _REACTIONIDENTIFIER
_REACTIONIDENTIFIER.oneofs_by_name['kind'].fields.append(
  _REACTIONIDENTIFIER.fields_by_name['value'])
_REACTIONIDENTIFIER.fields_by_name['value'].containing_oneof = _REACTIONIDENTIFIER.oneofs_by_name['kind']
_REACTIONIDENTIFIER.oneofs_by_name['kind'].fields.append(
  _REACTIONIDENTIFIER.fields_by_name['bytes_value'])
_REACTIONIDENTIFIER.fields_by_name['bytes_value'].containing_oneof = _REACTIONIDENTIFIER.oneofs_by_name['kind']
DESCRIPTOR.message_types_by_name['Reaction'] = _REACTION
DESCRIPTOR.message_types_by_name['ReactionIdentifier'] = _REACTIONIDENTIFIER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Reaction = _reflection.GeneratedProtocolMessageType('Reaction', (_message.Message,), {
  'DESCRIPTOR' : _REACTION,
  '__module__' : 'proto.small_pb2'
  # @@protoc_insertion_point(class_scope:ord.Reaction)
  })
_sym_db.RegisterMessage(Reaction)

ReactionIdentifier = _reflection.GeneratedProtocolMessageType('ReactionIdentifier', (_message.Message,), {
  'DESCRIPTOR' : _REACTIONIDENTIFIER,
  '__module__' : 'proto.small_pb2'
  # @@protoc_insertion_point(class_scope:ord.ReactionIdentifier)
  })
_sym_db.RegisterMessage(ReactionIdentifier)


# @@protoc_insertion_point(module_scope)
